apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-deployment
  namespace: project
  labels:
    app: project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      imagePullSecrets:
        - name: nexus-creds
      containers:
        - name: project
          image: 43.205.145.63:8000/project:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
